# WARNING: Temporarily disabled.
# Disable all builds, since Tea-CI provides better integration
# with MinGW.

language: cpp
notifications:
  email:
    recipients:
      - ahuszagh@gmail.com
    on_success: never
    on_failure: always
    on_cancel: never
    on_error: never

os:
  - linux
  - osx

install: true
script: true
